version: "3.9"
services:
    db:
        image: dlin/nfldb:version1
        volumes:
            - nfldb:/var/lib/postgresql/data
        ports:
            - 5432:5432
    redis:
        image: redis
        ports:
            - 6379:6379
volumes:
    nfldb:
        external: true
