version: "3.9"
services:
    db:
        image: nfldb_nfldb:latest
        volumes:
            - nfldb:/var/lib/postgresql/data
        ports:
            - 5433:5432
    redis:
        image: redis
        ports:
            - 6379:6379
volumes:
    nfldb:
        external: true
